[2023-01-16 21:13:45,670: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 2.00 seconds... (1/100)

[2023-01-16 21:13:52,679: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 4.00 seconds... (2/100)

[2023-01-16 21:14:01,684: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 6.00 seconds... (3/100)

[2023-01-16 21:14:12,691: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 8.00 seconds... (4/100)

[2023-01-16 21:14:25,704: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 10.00 seconds... (5/100)

[2023-01-16 21:14:40,712: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 12.00 seconds... (6/100)

[2023-01-16 21:24:59,907: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 2.00 seconds... (1/100)

[2023-01-16 21:25:06,917: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 4.00 seconds... (2/100)

[2023-01-16 21:25:15,926: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 6.00 seconds... (3/100)

[2023-01-16 21:25:26,934: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 8.00 seconds... (4/100)

[2023-01-16 21:25:39,944: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 10.00 seconds... (5/100)

[2023-01-16 21:25:54,951: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 12.00 seconds... (6/100)

[2023-01-16 22:19:13,017: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 2.00 seconds... (1/100)

[2023-01-16 22:19:20,027: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 4.00 seconds... (2/100)

[2023-01-16 22:19:29,036: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 6.00 seconds... (3/100)

[2023-01-16 22:19:40,044: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 8.00 seconds... (4/100)

[2023-01-16 22:19:53,053: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 10.00 seconds... (5/100)

[2023-01-16 22:20:08,061: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 12.00 seconds... (6/100)

[2023-01-16 22:20:39,342: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 2.00 seconds... (1/100)

[2023-01-16 22:20:46,349: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 4.00 seconds... (2/100)

[2023-01-16 22:20:55,357: ERROR/MainProcess] consumer: Cannot connect to redis://redis_server:6379/0: Error -3 connecting to redis_server:6379. Try again..
Trying again in 6.00 seconds... (3/100)

[2023-01-16 22:21:38,189: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-01-16 22:21:38,190: INFO/MainProcess] mingle: searching for neighbors
[2023-01-16 22:21:39,197: INFO/MainProcess] mingle: all alone
[2023-01-16 22:21:39,211: INFO/MainProcess] celery@fce3d62a60ba ready.
[2023-01-16 22:21:41,746: INFO/MainProcess] Task my_task[ee4d5569-482a-471e-a095-a2b044078d1d] received
[2023-01-16 22:21:41,753: INFO/ForkPoolWorker-7] Task my_task[ee4d5569-482a-471e-a095-a2b044078d1d] succeeded in 0.004778501000146207s: 'test task return string'
